#!/bin/bash

# Konfigurace Gitu
GIT_NAME=""
GIT_EMAIL=""

# Dotaz na jméno a e-mail, pokud nejsou definovány
if [[ -z "$GIT_NAME" ]]; then
    read -p "Zadejte vaše jméno pro Git: " GIT_NAME
fi

if [[ -z "$GIT_EMAIL" ]]; then
    read -p "Zadejte váš e-mail pro Git: " GIT_EMAIL
fi

# Nastavení jména a e-mailu pro Git
git config --global user.name "$GIT_NAME"
git config --global user.email "$GIT_EMAIL"

echo "Git byl úspěšně nakonfigurován:"
echo "Jméno: $GIT_NAME"
echo "E-mail: $GIT_EMAIL"
